options:
  merge-default-rules: true
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - '**/node_modules/**'
rules:
  indentation:
    - 2
    -
      size: 4
  nesting-depth:
    - 1
    -
      max-depth: 4
  no-color-literals:
    - 1
    -
      allow-rgba: true
  property-sort-order:
    - 1
    -
      order: smacss
      ignore-custom-properties: true
